FROM golang:1.26-alpine AS builder 

WORKDIR /app
COPY go.mod ./
RUN go mod download 

COPY . .
RUN go build -o main main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]