version: '3.8'

services:
    postgres:
        image: postgres:16-alpine
        container_name: posts_db 
        restart: always 
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: posts_app_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
    api-gateway-service:
        build:
            context: ./services/api-gateway
            dockerfile: Dockerfile
        container_name: api_gateway_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/api-gateway/.env.local
        ports:
            - "8000:8000"
        networks:
            - app-network
    user-service:
        build:
            context: ./services/user
            dockerfile: Dockerfile
        container_name: user_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/user/.env.local
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
    auth-service:
        build:
            context: ./services/auth
            dockerfile: Dockerfile
        container_name: auth_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/auth/.env.local
        ports:
            - "8081:8081"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
    post-service:
        build:
            context: ./services/post
            dockerfile: Dockerfile
        container_name: post_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/post/.env.local
        ports:
            - "8082:8082"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
    comment-service:
        build:
            context: ./services/comment
            dockerfile: Dockerfile
        container_name: comment_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/comment/.env.local
        ports:
            - "8083:8083"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
volumes:
    postgres_data:
networks:
    app-network:
        driver: bridge