version: '3.8'

services:
    postgres:
        image: postgres:16-alpine
        container_name: posts_db 
        restart: always 
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: posts_app_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init-schemas.sql
volumes:
    postgres_data: