version: '3.8'

services:
    postgres:
        image: postgres:16-alpine
        container_name: posts_db 
        restart: always 
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: posts_app_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
    api-gateway-service:
        build:
            context: ./services/api-gateway
            dockerfile: Dockerfile
        container_name: api_gateway_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/api-gateway/.env.local
        ports:
            - "8000:8000"
        networks:
            - app-network
    user-service:
        build:
            context: ./services/user
            dockerfile: Dockerfile
        container_name: user_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/user/.env.local
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
    auth-service:
        build:
            context: ./services/auth
            dockerfile: Dockerfile
        container_name: auth_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/auth/.env.local
        ports:
            - "8081:8081"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
    post-service:
        build:
            context: ./services/post
            dockerfile: Dockerfile
        container_name: post_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/post/.env.local
        ports:
            - "8082:8082"
        depends_on:
            postgres:
                condition: service_healthy
            kafka:
                condition: service_healthy
        networks:
            - app-network
    comment-service:
        build:
            context: ./services/comment
            dockerfile: Dockerfile
        container_name: comment_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/comment/.env.local
        ports:
            - "8083:8083"
        depends_on:
            postgres:
                condition: service_healthy
            kafka:
                condition: service_healthy
        networks:
            - app-network
    like-service:
        build:
            context: ./services/like
            dockerfile: Dockerfile
        container_name: like_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/like/.env.local
        ports:
            - "8084:8084"
        depends_on:
            postgres:
                condition: service_healthy
            kafka:
                condition: service_healthy
        networks:
            - app-network
    kafka:
        image: apache/kafka:latest
        container_name: kafka
        ports:
        - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_LOG_RETENTION_HOURS: 168
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 10
        networks:
            - app-network
    leaderboard-service:
        build:
            context: ./services/leaderboard
            dockerfile: Dockerfile
        container_name: leaderboard_service
        restart: unless-stopped
        env_file:
            - configs/.env.global
            - services/leaderboard/.env.local
        ports:
            - "8085:8085"
        depends_on:
            postgres:
                condition: service_healthy
            kafka:
                condition: service_healthy
        networks:
            - app-network
    redis:
        image: redis:7-alpine
        container_name: redis_service
        ports:
        - "6379:6379"
        volumes:
        - redis_data:/data
        command: redis-server --appendonly yes
        restart: unless-stopped
        networks:
            - app-network
volumes:
    postgres_data:
    redis_data:
networks:
    app-network:
        driver: bridge