CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS posts;
CREATE SCHEMA IF NOT EXISTS comments;
CREATE SCHEMA IF NOT EXISTS likes;

GRANT ALL PRIVILEGES ON SCHEMA users TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA posts TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA comments TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA likes TO postgres;